name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name: 'Build'
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build FMCB'
        # Default value if no value is explicitly provided
        default: 'ok'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
